# Generated by Django 6.0.1 on 2026-01-20 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dharma', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Dharma.category'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
